apiVersion: v1
kind: Service
metadata:
  name:  myfirstservice
spec:
  selector:
    app:  myfirstjenkins
  type: NodePort
  ports:
  - name:  name-of-the-port
    port:  8080
    nodePort:  30003
    protocol:  TCP
