apiVersion: v1
kind: ReplicationController
metadata:
  name: myfirstjenkinsrc
spec:
  replicas: 4
  selector:
    app: myfirstjenkins
  template:
    metadata:
      name: myfirstjenkins
      labels:
        app: myfirstjenkins
    spec:
      containers:
        - name: myfirstjenkins
          image: jenkins
          ports:
            - containerPort: 8080

