apiVersion: v1
kind: Service
metadata:
  name:  mytomcatservice
spec:
  selector:
    app:  mytomcatapp
  type: NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    nodePort:  30002
    protocol:  TCP
