apiVersion: v1
kind: ReplicationController
metadata:
  name: mytomcat
spec:
  replicas: 2
  selector:
    app: mytomcatapp
  template:
    metadata:
      name: mytomcatapp
      labels:
        app: mytomcatapp
    spec:
      containers:
        - name: mytomcatapp
          image: tomcat
          ports:
            - containerPort: 80

