apiVersion: v1
kind: Service
metadata:
  name: springpetclinic-service
  labels:
    name: springpetclinic
spec:
  type: {{ .Values.service.type }}
  selector:
    app: springpetclinic
  ports:
  - port: {{ .Values.service.port }}
    
