# Default values for tomcat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: docker.io/satishyelloju/springpetclinic
  tag: v1.0.0
  pullPolicy: IfNotPresent


service:
  type: LoadBalancer
  port: 8080

