apiVersion: v1 # for versions before 1.9.0 use apps/v1be
kind: Pod
metadata:
  name: nginx-satya
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9
    ports:
    - containerPort: 80
      #    volumeMounts:
      #    - name: mydata
      #      mountPath: /usr/share/nginx/html
      #  volumes:    
      #  - name: mydata
      #    hostPath:
      #      path: /home/satikumar0685/
      #  emptyDir: {}            
     
