apiVersion: v1
kind: Service
metadata:
  name: my-tomcat-service
  labels:
    name: testspring
spec:
  type: {{ .Values.service.type }}
  selector:
    app: testspring
  ports:
  - port: {{ .Values.service.port }}
    
